### ISSUE TITLE
why class attribute

### ISSUE THREAD

**Issue by metadings** [syntaxhighlighter/syntaxhighlighter#114]
Why do you use the colon (:) in the html class attribute, the css-name or className attribute?

I noticed that MDN uses SyntaxHighlighter, but v1.5.1, where SH did not misuse the class attribute...
Is there any way to get you using another attribute (also without data- what google and ms also don't do)?

Use syntax-highlighter="ruler: false; minDigits: 2" ! HTML class attribute is only for CSS valid names!!

**Comment by alexgorbatchev** [comment]
Duplicated by #302.
