### ISSUE TITLE
two-digit numbers disappear

### ISSUE THREAD

**Issue by nawroth** [syntaxhighlighter/syntaxhighlighter#15]
When i use SyntaxHighlighter 3.0.83 on pre-elements where the only content is a two-digit number, the output is a single &amp;nbsp; and nothing else. One or three digits works just fine, but not two digits. I thought it was a brush problem (using JScript brush), but get the same behavior with the plain brush.

Example HTML: 
&lt;pre class=&quot;programlisting brush: javascript&quot;&gt;42&lt;/pre&gt;

Settings in use:
    SyntaxHighlighter.defaults[&#39;tab-size&#39;] = 4;
    SyntaxHighlighter.defaults[&#39;gutter&#39;] = false;
    SyntaxHighlighter.defaults[&#39;toolbar&#39;] = false;

This is the generated HTML:
&lt;div class=&quot;syntaxhighlighter nogutter  javascript&quot; id=&quot;highlighter_441860&quot;&gt;&lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td class=&quot;code&quot;&gt;&lt;div class=&quot;container&quot;&gt;&lt;div class=&quot;line number1 index0 alt2&quot;&gt;&amp;nbsp;&lt;/div&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;/div&gt;

**Comment by gordon-fish** [comment]
I've submitted a fix #467 for this.
