### ISSUE TITLE
Doesn't play nice with Bootstrap

### ISSUE THREAD

**Issue by nmakarov** [syntaxhighlighter/syntaxhighlighter#167]
... since Bootstrap css tweaks selectors .container:before and .container:after. 

As a result, the whole code div shifts about 15 pixels down (related to the gutter) and line numbering becomes thrown out of sync with the code. Confirmed in Firefox 10.0.7 under CentOS. 

After some consideration I have replaced the class name from ".container" to ".shcontainer" - two modifications in shCore.js and three in shCore.css.

**Comment by tristantao** [comment]
I know this is old, but bump @davidcroda for the awesome working answer.

OS X 10.9.5
Doesn't interfere with *Chrome 40.0.2214.111*
Fixes the issue on *Firefox 35.0.1*

**Comment by alexgorbatchev** [comment]
Should be fixed by https://github.com/syntaxhighlighter/theme-base/commit/70d2b3b3ff2a7b0b29539878d66c51e93e360bce
