### ISSUE TITLE
Python string highlighting bug

### ISSUE THREAD

**Issue by jacktrades** [syntaxhighlighter/syntaxhighlighter#19]
Everything between two sequences of '"' (single quote, double quote, single quote) is highlighted as a string.

a = '"' # single/double/single quote
  # everything between a and c is highlighted as a string
c = '"' # single/double/single quote

This only happens when there are 2 '"' sequences.  If one of those sequences uses '\"' or inserts spaces ' " " the code between them is not highlighted as a string.

**Comment by alexgorbatchev** [comment]
I'll be looking closer at #72
