### ISSUE TITLE
SyntaxHighlighter should accept already loaded XRegExp in more recent version

### ISSUE THREAD

**Issue by FrViPofm** [syntaxhighlighter/syntaxhighlighter#207]
I use XRegExp in other libraries, and I need v. 2.0.
It is nice that SyntaxHighlighter comes with embeded XRegExp, but when a more recent version is used, it would be nice that SyntaxHighlighter would accept it.

Thanks for your work.

**Comment by alexgorbatchev** [comment]
SyntaxHighlighter now bundles own version of `XRegExp` and doesn't expose it to the window unless `--compat` flag is passed during the build.

**Comment by alexgorbatchev** [comment]
f7c4d6204c9d4486681f1b54ba15a2bc1171c5d5 fixes this issue in v4
