### ISSUE TITLE
Might have compatibility Issues with Bootstrap.

### ISSUE THREAD

**Issue by huntzhan** [syntaxhighlighter/syntaxhighlighter#275]
Both SyntaxHighlighter and Bootstrap define .container  CSS class, which cause the lines of 'gutter' can not align with the lines of code. 

.container:after {
    content: " ";
...
}
After forbidding 'content' of '.container:after' in bootstrap.css, the problem can be solved temporarily.

**Comment by alexgorbatchev** [comment]
This should be resolved by https://github.com/syntaxhighlighter/theme-base/commit/70d2b3b3ff2a7b0b29539878d66c51e93e360bce. Thank you very much for taking time to report the issue!
