### ISSUE TITLE
Code in view source mode invisible for Chrome on Mac

### ISSUE THREAD

**Issue by theresam** [syntaxhighlighter/syntaxhighlighter#342]
Inside the syntax highlighter block is a "view source" icon. Clicking on this icon will trigger a new window with the code inside of it. This functionality works in Chrome (PC), FireFox (PC/Mac), Safari (Mac), and IE 11-9.  For some reason when using Chrome on a Mac, the code inside of the new window is invisible until you highlight it or inspect it with dev tools. I went to the SyntaxHighlighter demo page and noticed the exact same thing happening.

Here is a video of it happening on our site. http://screencast.com/t/dSiFIBdUdPLo
Here is a video of it happening on your demo site. http://screencast.com/t/uN591CjXYrv

There were a couple computers where this bug didn't happen, but the majority of the computers tested were able to duplicate the bug. Computers have been rebooted and had the cache cleared. The following is a list of computers with their OS versions and Chrome versions. I haven't seen a correlation yet and I'm not sure if this is a SyntaxHighlighter bug or a Chrome bug.

No bug
OSX 10.9.4     Chrome Dev 39.0.2145.4
OSX 10.9.4     Chrome 37.0.2062.94

Has bug
OSX 10.9.2     Chrome 37.0.2062.120
OSX 10.9.4     Chrome 37.0.2062.120
OSX 10.9.4     Chrome 37.0.2062.120
OSX 10.9.3     Chrome 37.0.2062.94
OSX 10.9.4     Chrome 37.0.2062.94

**Comment by alexgorbatchev** [comment]
This is a very old feature that is no longer developed.
