### ISSUE TITLE
I have to declare what program language I want to highlight ?

### ISSUE THREAD

**Issue by hojas** [syntaxhighlighter/syntaxhighlighter#348]
```
<pre class="brush: js">
    /**
     * SyntaxHighlighter
     */
    function foo()
    {
        if (counter <= 10)
            return;
        // it works!
    }
</pre>
```

If I want to highlight this , I have to add `class="brush: js"`, but I do not know what the language is that will be highlight sometimes. What should I do with this ?

**Comment by SoboLAN** [comment]
Well, since most languages are C-derivatives, you could use that as a fallback.
