### ISSUE TITLE
3.0.83 Is Newer Than 3.0.9

### ISSUE THREAD

**Issue by GrahamCampbell** [syntaxhighlighter/syntaxhighlighter#350]
That's a bit of a mess for versioning...

**Comment by alexgorbatchev** [comment]
Where are you seeing this?

**Comment by GrahamCampbell** [comment]
Bower will install it if i ask for `~3.0.8` rather than the latest. The behaviour is the same for `~3.0.9` too.

**Comment by alexgorbatchev** [comment]
Interesting... that's bower's faulty semver parser :(

**Comment by GrahamCampbell** [comment]
No its not. It's correct. Your versioning is incorrect. 83 is a larger patch version than 9...

**Comment by alexgorbatchev** [comment]
I see what's going on.

**Comment by dotmagic** [comment]
I have been also slightly confused.
Please just release another v3.1.0 or change 3.0.9 to 3.0.90, after more then 10 years this awesome script really deserves a higher number :)

Oh, and please be so kind to Update the Download Page:
http://alexgorbatchev.com/SyntaxHighlighter/download/

There are still many outdated confusing links on your website.

**Comment by alexgorbatchev** [comment]
https://github.com/syntaxhighlighter/syntaxhighlighter/releases/tag/v3.0.90

Thank you very much everyone for taking time to flag this issues!

**Comment by HassanRafay** [comment]
I am new to github and using files from git. I am trying to use syntax highlighter and I am not sure how to include it in my html file. It would be wonderful if you can help me with it
