### ISSUE TITLE
[bug] in spring mvc 4.x

### ISSUE THREAD

**Issue by liefdiy** [syntaxhighlighter/syntaxhighlighter#352]
there is a annotation key word named "@MatrixVariable",  when java code contains MatrixVariable,  it'll add a <string,> in the end. like this:
    
	// /user/matrix4/asaa/pets/aa;q=11;r=12 输出{}, {q=[11], r=[12]}
	@RequestMapping(value = "/matrix4/{ver}/pets/{petId}", method = RequestMethod.GET)
	public String matrix4(@MatrixVariable(pathVar = "ver") Map<string, string=""> mtx1, @MatrixVariable(pathVar = "petId") Map<string, string=""> mtx2, Model model) {
	    System.out.println(mtx1);
	    System.out.println(mtx2);
	    return "/user/index";
	}
	</string,></string,>

I think it may be lack of key work,how to fix it ?

**Comment by alexgorbatchev** [comment]
You have to HTML escape `<` characters. See http://alexgorbatchev.com/SyntaxHighlighter/manual/installation.html for details.
