### ISSUE TITLE
syntaxhighlighter omits some HTML content in pre tags.

### ISSUE THREAD

**Issue by everthis** [syntaxhighlighter/syntaxhighlighter#355]
the rendered webpage is

![syntax](https://cloud.githubusercontent.com/assets/3142886/6434345/ad8f1dba-c0c1-11e4-887d-2bc5f49a9631.jpg)

while the code is

   	
	
	
	
	 <html class=""> 

The code 

       <html class="">
is omitted.

**Comment by alexgorbatchev** [comment]
Are you escaping `<`? See http://alexgorbatchev.com/SyntaxHighlighter/manual/installation.html for details.
