### ISSUE TITLE
Single quote is getting escaped in code 

### ISSUE THREAD

**Issue by jassics** [syntaxhighlighter/syntaxhighlighter#360]
Hi,
Is there anything that I am missing?
I am using Syntax Highlighter in MyBB forum and while displaying any code where single quote is used it is simply escaping due to which if someone copies that quote it will throw an error.

Sample code that I wrote:

```
#Show reverse lookup value of an IP Address 
sub show_ip_lookup {   
  my $answer = $res->query($ip_address->reverse_ip(),'PTR'); 
  my $namer  = $answer->{'answer'}[0]; 
  print "Reverse lookup: $namer->{'ptrdname'}\n" if(defined $namer->{'ptrdname'}); 
} 
```

But it's getting converted as:

```
#Show reverse lookup value of an IP Address 
sub show_ip_lookup {   
  my $answer = $res->query($ip_address->reverse_ip(),\'PTR\'); 
  my $namer  = $answer->{\'answer\'}[0]; 
  print "Reverse lookup: $namer->{\'ptrdname\'}\n" if(defined $namer->{\'ptrdname\'}); 
} 
```

Can anyone help me to troubleshoot this issue?

**Comment by alexgorbatchev** [comment]
What language is this?

**Comment by jassics** [comment]
@alexgorbatchev It's Perl

**Comment by alexgorbatchev** [comment]
Moved to https://github.com/syntaxhighlighter/brush-perl/issues/1
