### ISSUE TITLE
Complete repack and better instructions

### ISSUE THREAD

**Issue by BramVanroy** [syntaxhighlighter/syntaxhighlighter#362]
This project once was great, and the core is still an awesome tool, but for a beginner this tool is a pain to install. A couple of things that need fixing:

**Version control and setting**
The latest stable version that's on GitHub and on the website aren't the same - or at least don't contain the same files. It isn't clear either which version is on this page, and which is stable and so on.

Furthermore, instructions that differ between versions aren't set anywhere.

**Stable 3.0.9**
Using the source files in the compressed file that is linked simply doesn't work. [This](http://blog.blakesimpson.co.uk/read/5-installing-syntaxhighlighter-error-xregexp-not-defined) seems to solve the problem, but then again it seems that I am mixing versions and I'm not at all sure what I'm doing is even remotely correct.

I wonder whether any of this will ever get fixed, or if focus lies on 4.0. Tool is great - but instructions aren't clear.

**Comment by alexgorbatchev** [comment]
I'm about to merge #dev branch, it's a complete rework of bundling and full modularization of the original source.
