### ISSUE TITLE
All code in one line.

### ISSUE THREAD

**Issue by tmacjx** [syntaxhighlighter/syntaxhighlighter#363]
I'm using Summernote editor in my django-project.
when I add some code in it,I found  all code in one line.
Could Anyone help me?
Or same problem?

![2015-07-07 11 45 03](https://cloud.githubusercontent.com/assets/11555807/8538373/f1a710c6-249d-11e5-84d7-0b02ce4d98f6.png)
![2015-07-07 11 45 22](https://cloud.githubusercontent.com/assets/11555807/8538376/f78b50ec-249d-11e5-8377-611786539da9.png)
![2015-07-07 11 45 41](https://cloud.githubusercontent.com/assets/11555807/8538375/f61962e4-249d-11e5-968f-c3193c86498f.png)

**Comment by tmacjx** [comment]
![2015-07-07 10 35 44](https://cloud.githubusercontent.com/assets/11555807/8537607/f801af62-2493-11e5-960e-0fe448aef7f7.png)

**Comment by alexgorbatchev** [comment]
This might be the editor issue.
