### ISSUE TITLE
Escaped line breaks in C

### ISSUE THREAD

**Issue by tnaia** [syntaxhighlighter/syntaxhighlighter#364]
In C, line breaks may be escaped (backslash followed by newline).

Below, only the first line is treated as a macro definition.

    #define OOPS do{                           \
            fprintf (stderr, "\n! OOps!\n");   \
            exit(1);                           \
            while(0);

Something similar happens with

    printf("asd \
         bchas%d", 3);
    return 0;

**Comment by alexgorbatchev** [comment]
Moved to the brush repo.
