### ISSUE TITLE
quote on comments

### ISSUE THREAD

**Issue by ttecles** [syntaxhighlighter/syntaxhighlighter#365]
In SQL when there is a quote inside a comment, all the match for the consequent comments go wrong:

-- this is a comment with a quote '
        DBMS_OUTPUT.put_line ('This is a string to be highlighted');

the string 'This is a string to be highlighted' is not highlighted due to the first quote in the comment

![image](https://cloud.githubusercontent.com/assets/14053903/10191282/dac2c608-6772-11e5-96a6-d4449739f129.png)

**Comment by alexgorbatchev** [comment]
Moved to the brush repo.
