### ISSUE TITLE
HTML elements inside PRE blocks get escaped

### ISSUE THREAD

**Issue by mchatzi** [syntaxhighlighter/syntaxhighlighter#366]
If the original HTML contains additional HTML elements inside the PRE block, like the &lt;strong&gt; element shown here:
&lt;pre class="brush: java"&gt;String query = &lt;strong&gt;QueryBuilder&lt;/strong&gt;.build()&lt;/pre&gt;

then the syntax highlighter replaces &lt;strong&gt; with &amp;lt;strong&amp;gt; so the string "&lt;strong&gt;" appears as is in the output:

1. String query = &lt;strong&gt;QueryBuilder&lt;/strong&gt;.build()</pre>

Shouldn't the highlighter leave these HTML elements intact?

**Comment by alexgorbatchev** [comment]
You have to HTML escape `<`. See http://alexgorbatchev.com/SyntaxHighlighter/manual/installation.html.

**Comment by mchatzi** [comment]
Well, in our system authors use a wysiwyg editor to create the HTML, so escaping the generated html  manually is not a solution.
