### ISSUE TITLE
stripe-background and custom options

### ISSUE THREAD

**Issue by zenithtekla** [syntaxhighlighter/syntaxhighlighter#368]
Hi,
I tried this highlighter before and can't attain full options and line stripes..Many many websites have all that in it.

See "syntax1.png" photo for what I'm mentioning:
https://drive.google.com/folderview?id=0B4ruhRenMo6kV0VqenphTE41R1k&usp=sharing

Any idea on how to implement/configure syntaxhighlighter for that?
Thanks & regards,
Zenith

**Comment by alexgorbatchev** [comment]
The screenshot is from a different script. I think it might be a fork.
