### ISSUE TITLE
C# Expression-bodied function

### ISSUE THREAD

**Issue by dalealleshouse** [syntaxhighlighter/syntaxhighlighter#371]
If you a C# expression body member, extra xml is added to the end of the code block. You can see this here: http://hideoushumpbackfreak.com/post/2015/12/21/Turing-Machine-Simulation-in-C

![capture](https://cloud.githubusercontent.com/assets/4975687/11922217/ee8d12da-a762-11e5-8e42-cd8b57051fb3.PNG)

**Comment by alexgorbatchev** [comment]
You have to HTML escape `<`. See http://alexgorbatchev.com/SyntaxHighlighter/manual/installation.html.

**Comment by dalealleshouse** [comment]
There are no < characters in the code. I'm sorry if I'm missing something obvious.

**Comment by alexgorbatchev** [comment]
`IEnumerable<transition>`
