### ISSUE TITLE
SyntaxHighlighter Not Working in Chrome on Mac OS X (El Capitan)

### ISSUE THREAD

**Issue by tonysneed** [syntaxhighlighter/syntaxhighlighter#379]
I have a Wordpress.com blog where I post code snippets using SyntaxHighlighter.  However, the code is not highlighted when viewing my blog in Google Chrome on a Mac.  All other browsers / platforms seem to show the code correctly highlighted.

Here is a blog post that shows the behavior: http://blog.tonysneed.com/2016/02/27/visual-studio-code-typescript-part-2/

Here is a screenshot of the post in Chrome on a Mac.

![wp-code-chrome](https://cloud.githubusercontent.com/assets/2836367/13488381/22fb3b08-e121-11e5-87ae-1e6f09ee893b.png)

Thanks,
Tony Sneed

**Comment by alexgorbatchev** [comment]
Which chrome version? Could you check the console for errors?

**Comment by tonysneed** [comment]
You can close this now.  I re-installed Google Chrome on my Mac, and the syntax highlighting works now.  Thanks!
