### ISSUE TITLE
Best way to obtain compiled version?

### ISSUE THREAD

**Issue by k0105** [syntaxhighlighter/syntaxhighlighter#431]
Hello,

as was previously (and impolitely) asked in https://github.com/syntaxhighlighter/syntaxhighlighter/issues/389 - is there a compiled version available and if so, what is the best way to obtain it? Compiling fails for me in the final step during loading Gruntfile.coffee and I'd be fine with just using it for now instead of figuring out what the problem is.

Thank you in advance.

Best wishes,
k0105

**Comment by m-hatch** [comment]
The build process seems to be failing for Gulp builds as well. See #428. Having a dist with the compiled files would be helpful.

**Comment by k0105** [comment]
I just switched to `highlight.js` (cmp. https://github.com/isagalaev/highlight.js) which works well for me.

**Comment by karljacuncha** [comment]
There are a few build issues, mostly related to Promises.
I've managed to get it building (enough for me at least), with these changes:
https://github.com/karljacuncha/syntaxhighlighter/commit/dc015fa299d4d249e8518664e205a838c55372cf
