### ISSUE TITLE
Which languages are supported?

### ISSUE THREAD

**Issue by ShalokShalom** [syntaxhighlighter/syntaxhighlighter#433]
From your Readme, you cant say which languages are supported.

**Comment by yumetodo** [comment]
You can manually add languages support when you cannot find brush.

**Comment by ShalokShalom** [comment]
And which languages are supported?

**Comment by yumetodo** [comment]
@ShalokShalom Have you ever check below?
https://github.com/syntaxhighlighter?utf8=%E2%9C%93&q=brush&type=&language=
When you cannot find the language you want, google that or write manually.

**Comment by ShalokShalom** [comment]
Some people (like me) land on this page directly coming from Google and Co
I just committed an entry for the Readme, thanks a lot
