### ISSUE TITLE
[Javascript Brush] Specifying strings with single quotes in functions.

### ISSUE THREAD

**Issue by joesavage** [syntaxhighlighter/syntaxhighlighter#55]
Hi,

I was recently writing a tutorial on my website, only to find when publishing it that the syntax highlighting had really screwed up (for some reason unknown to me).
As can be demonstrated, here: http://www.dev-hq.net/7-Javascript/54-If-and-Else-statements
Using strings that are created using single quotes (apostrophes) inside a function, seems to really mess up the JScript SyntaxHighlighting. Like so:

<pre class="brush: js;">
var name = prompt('What is your name?');
if(name=='Joe') //If the user's name is 'Joe'
{
	alert('Wow, cool – my name is Joe too!');
}
else if(name=='Fred') //If the user's name is 'Fred'
{
	alert('Fred is a pretty generic name...');
}
else if(name=='John') //If the user's name is 'John'
{
	alert('Alright, John?');
}
else if(name=='George') //If the user's name is 'George'
{
	alert('George is a pretty decent name.');
}
else
{
	alert('I have no opinion on your name.');
}
</pre>

**Comment by alexgorbatchev** [comment]
I'll be looking closer at #72
